mode: rule
port: 7890
allow-lan: false
ipv6: true
tcp-concurrent: true
keep-alive-interval: 25
unified-delay: false

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  use-hosts: true
  ipv6: true
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  nameserver:
    - https://8.8.8.8/dns-query#PROXY
    - https://8.8.4.4/dns-query#PROXY
    - 8.8.8.8
    - 8.8.4.4

geodata-mode: true
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

{{ conf | except("proxy-groups", "port", "mode") | yaml }}

proxy-groups:
- name: 'PROXY'
  type: 'url-test'
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}
{{ conf.get("proxy-groups", []) | yaml }}

rule-providers:
  PROXY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/PROXY.yaml
    path: ./rebullet/PROXY.yaml
    interval: 86400
  REJECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/REJECT.yaml
    path: ./rebullet/REJECT.yaml
    interval: 86400
  CLOUDFLARE:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cloudflare.yaml 
    path: ./rebullet/CLOUDFLARE.yaml
    interval: 86400
  GOOGLE:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/google.yaml
    path: ./rebullet/GOOGLE.yaml
    interval: 86400
  FASTLY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/fastly.yaml
    path: ./rebullet/FASTLY.yaml
    interval: 86400
  CLOUDFRONT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cloudfront.yaml
    path: ./rebullet/CLOUDFRONT.yaml
    interval: 86400
rules:
  - RULE-SET,PROXY,PROXY
  - RULE-SET,REJECT,REJECT
  - RULE-SET,CLOUDFLARE,PROXY
  - RULE-SET,GOOGLE,PROXY
  - RULE-SET,FASTLY,PROXY
  - RULE-SET,CLOUDFRONT,PROXY
