mixed-port: 2080
allow-lan: false
tcp-concurrent: true
enable-process: true
global-client-fingerprint: chrome
mode: rule
ipv6: true
keep-alive-interval: 25
unified-delay: false

{{ conf | except("proxy-groups", "port", "mode") | yaml }}

geodata-mode: true 
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
    - '[::]:53'
  auto-route: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  listen: 0.0.0.0:53
  use-hosts: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - 'localhost'
  default-nameserver:
    - 9.9.9.9
    - 149.112.112.112
  nameserver:
    - https://dns.quad9.net/dns-query#PROXY
  fallback:
    - tls://dns.quad9.net#PROXY
  proxy-server-nameserver:
    - https://dns.quad9.net/dns-query

proxy-groups:
- name: 'PROXY'
  type: 'url-test'
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}
{{ conf.get("proxy-groups", []) | yaml }}

rule-providers:
  GOOGLE:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/google.yaml
    path: ./rebullet/google.yaml
    interval: 86400
  CLOUDFLARE:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cloudflare.yaml
    path: ./rebullet/cloudflare.yaml
    interval: 86400
  FASTLY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/fastly.yaml
    path: ./rebullet/fastly.yaml
    interval: 86400
  CLOUDFRONT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cloudfront.yaml
    path: ./rebullet/cloudfront.yaml
    interval: 86400
  PROXY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/PROXY.yaml
    path: ./rebullet/proxy.yaml
    interval: 86400
  REJECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/REJECT.yaml
    path: ./rebullet/reject.yaml
    interval: 86400
  DIRECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/DIRECT.yaml
    path: ./rebullet/direct.yaml
    interval: 86400
    
rules:
  - RULE-SET,DIRECT,DIRECT
  - RULE-SET,PROXY,PROXY
  - RULE-SET,REJECT,REJECT
  - RULE-SET,CLOUDFLARE,PROXY
  - RULE-SET,GOOGLE,PROXY
  - RULE-SET,CLOUDFRONT,PROXY
  - RULE-SET,FASTLY,PROXY
