mode: rule
port: 7890
allow-lan: false
ipv6: true
tcp-concurrent: true
keep-alive-interval: 25
unified-delay: false
log-level: info

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
    - '[::]:53'
  auto-route: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  listen: 0.0.0.0:53
  use-hosts: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - 'localhost'
  default-nameserver:
    - 9.9.9.9
    - 149.112.112.112
  nameserver:
    - https://dns.quad9.net/dns-query#PROXY
  fallback:
    - tls://dns.quad9.net#PROXY
  proxy-server-nameserver:
    - https://dns.quad9.net/dns-query

geodata-mode: true
geox-url:
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

{{ conf | except("proxy-groups", "port", "mode") | yaml }}

proxy-groups:
- name: 'REBULLET'
  type: 'url-test'
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}
{{ conf.get("proxy-groups", []) | yaml }}

proxy-groups:
 - name: 'PROXY'
   type: 'url-test'
   url: 'http://www.gstatic.com/generate_204'
   interval: 300
   proxies:
   {{ proxy_remarks | yaml | indent(2) }}
 {{ conf.get("proxy-groups", []) | yaml }}
 
 rule-providers:
   CLOUDFLARE:
     type: http
     behavior: classical
     format: yaml
     url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cloudflare.yaml 
     path: ./rebullet/CLOUDFLARE.yaml
     interval: 86400
   GOOGLE:
     type: http
     behavior: classical
     format: yaml
     url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/google.yaml
     path: ./rebullet/GOOGLE.yaml
     interval: 86400
   FASTLY:
     type: http
     behavior: classical
     format: yaml
     url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/fastly.yaml
     path: ./rebullet/FASTLY.yaml
     interval: 86400
   CLOUDFRONT:
     type: http
     behavior: classical
     format: yaml
     url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cloudfront.yaml
     path: ./rebullet/CLOUDFRONT.yaml
     interval: 86400
     
 rules:
   - RULE-SET,CLOUDFLARE,PROXY
   - RULE-SET,GOOGLE,PROXY
   - RULE-SET,FASTLY,PROXY
   - RULE-SET,CLOUDFRONT,PROXY
